#!/bin/bash

# create ~/bin and add it to $PATH
mkdir -p ~/bin
export PATH="$PATH:$HOME/bin"

# install homebrew
if [ $(uname) == 'Darwin' ]; then
        if [ ! -x $(command -v brew) ]; then
                echo Installing homebrew...
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                export HOMEBREW_BUNDLE_FILE=/Users/Kabir/.Brewfile
        fi
        echo homebrew installed.
fi

# install void-packages
if [ -x "$(command -v lsb_release)" ]; then
        if [ $(lsb_release -si) == 'VoidLinux' ]; then
        if [ ! -e ~/void-packages ]; then
                echo "cloning void-packages and setting up xbps-src"
                git clone https://github.com/void-linux/void-packages/ && cd void-packages
                ./xbps-src binary-bootstrap
                cd
        fi
        echo void-packages installed.
        fi
fi

# install omz
if [ ! -e ~/.oh-my-zsh ]; then
        echo oh-my-zsh not found. \n Installing omz...
        #sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi
echo oh-my-zsh installed.

# install zsh-syntax-highlighting
if [ ! -e ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ]; then
        echo zsh-syntax-highlighting not found. \n Installing zsh-syntax-highlighting...
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi
echo zsyh-syntax-highlighting installed.

# install zsh-autosuggestions
if [ ! -e ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
        echo zsh-autosuggestions not found. \n Installing zsh-autosuggestions. . .
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi
echo zsh-autosuggestions installed.

# install pfetch
if [ ! -x "$(command -v pfetch)" ]; then
        echo pfetch not found. \n Installing pfetch. . .
        if [ -x "$(command -v brew)" ]; then brew install pfetch
        elif [ -x "$(command -v dnf)" ]; then sudo dnf install pfetch
        elif [ -x "$(command -v pacman)" ]; then sudo pacman -S pfetch
        elif [-x "$(command -v pkg)" ]; then sudo pkg install pfetch
        elif [-x "$(command -v xbps)" ]; then sudo xbps-install -S pfetch
        else
                git clone https://github.com/dylanaraps/pfetch
                cd pfetch
                echo Installing pfetch
                sudo make install
        fi
fi
echo pfetch installed.

# brew bundle
if [ -x "$(command -v brew)" ]; then
        echo -n "run brew bundle? " 
        read ans
        if [[ $ans == 'y' || $ans == 'Y' ]]; then
                brew bundle --global
                echo all homebrew packages are installed and up-to-date.
        fi
        echo bootstrap all done, exiting now...
fi
