#!/bin/bash

# load the scripting addition automatically for macOS Big Sur
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config active_window_opacity        0.95
yabai -m config normal_window_opacity        0.9
yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xffef0e12
yabai -m config normal_window_border_color   0xffef8f91
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m space 1 --label mail/skype
yabai -m space 2 --label AC/general
yabai -m space 3 --label web
yabai -m space 4 --label study
yabai -m space 5 --label extra

# bar stuff
yabai -m config external_bar         all:$(spacebar -m config height):0

# caffienate while AC is running
while [ $(pidof "Adobe Connect") != $(pidof "Adobe Connect ") ]; do caffeinate; done

echo "yabai configuration loaded.."
