#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ "$(hostname)" == "iMac" ]; then
    xrandr -s 1920x1080
fi

if [[ $(xinput --list-props "Apple Inc. Magic Trackpad 2") ]]; then
	xinput --set-prop "Apple Inc. Magic Trackpad 2" "libinput Natural Scrolling Enabled" 1
	xinput --set-prop "Apple Inc. Magic Trackpad 2" "libinput Tapping Enabled" 1
fi

xsetroot -cursor_name left_ptr

polybar status
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              0
bspc config focus_follows_pointer   true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a thunderbird desktop='^1'
bspc rule -a skypeforlinux desktop='^1'
bspc rule -a firefox desktop='^3'
