#!/bin/bash

#autostart programs
pgrep -x sxhkd > /dev/null || sxhkd &
xscreensaver --no-splash &
polybar status &
(bin/backup.sh >& .local/share/backup.log) &
(onedrive_tray --onedrive-path "/usr/sbin/onedrive" --onedrive-args "-m --enable-logging") &
spotifyd --no-daemon &
playerctld daemon

#imac customizatiosn
if [ "$(hostname)" == "iMac" ]; then
    xrandr -s 3840x2160
fi

#x session config
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
xinput --set-prop "Nordic 2.4G Wireless Receiver Mouse" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "Nordic 2.4G Wireless Receiver Mouse" "libinput Accel Speed" -1
~/.fehbg

#general bspwm config
bspc monitor -d I II III IV V VI VII VIII IX
bspc config border_width            2
bspc config window_gap              0
bspc config focus_follows_pointer   true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#app rules
bspc rule -a Thunderbird desktop='^1'
bspc rule -a Firefox desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

echo bspwm configuration loaded.
